services:
  accounts:
    image: "shivamwadkar/accounts:v1"
    container_name: accounts-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - fintech
  cards:
    image: "shivamwadkar/cards:v1"
    container_name: cards-service
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - fintech
  loans:
    image: "shivamwadkar/loans:v1"
    container_name: loans-service
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - fintech
networks:
  fintech:
    driver: "bridge"